import time
import os
os.system('cls')
product = "laptop"
lijst1 = ['factory']
lijst2 = ['distribution']
lijst3 = ['shop']
time.sleep(1)
print(lijst1)
print(lijst2)
print(lijst3)
time.sleep(1)
os.system('cls') 
lijst1.append(product)
print(lijst1)
print(lijst2)
print(lijst3)
time.sleep(1)
os.system('cls') 
lijst1.remove(product)
lijst2.append(product)
print(lijst1)
print(lijst2)
print(lijst3)
time.sleep(1)
os.system('cls')
lijst2.remove(product)
lijst3.append(product)
print(lijst1)
print(lijst2)
print(lijst3)
time.sleep(1)
os.system('cls')
lijst3.remove(product)
print(lijst1)
print(lijst2)
print(lijst3)
time.sleep(1)